# Generated by Django 5.2.5 on 2025-08-24 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SOFData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("extracted_data", models.JSONField()),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SoFDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("file", models.FileField(upload_to="sof_documnents/")),
                (
                    "file_type",
                    models.CharField(
                        choices=[("pdf", "PDF"), ("word", "Word")], max_length=11
                    ),
                ),
                ("uplaoded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
