# Generated by Django 5.2.5 on 2025-08-24 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("pipeline", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sofdocument",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sof_documents",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sofdata",
            name="documnent",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sof_date",
                to="pipeline.sofdocument",
            ),
        ),
    ]
