# Generated by Django 5.2.5 on 2025-08-25 05:00

import django.db.models.deletion
import pipeline.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pipeline", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sofdocument",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "SoF Document",
                "verbose_name_plural": "SoF Documents",
            },
        ),
        migrations.RenameField(
            model_name="sofdocument",
            old_name="uplaoded_at",
            new_name="uploaded_at",
        ),
        migrations.AddField(
            model_name="sofdata",
            name="confidence_score",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="sofdocument",
            name="file_name",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="sofdocument",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("compleated", "Compleated"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=12,
            ),
        ),
        migrations.AlterField(
            model_name="sofdata",
            name="documnent",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="extracted_data",
                to="pipeline.sofdocument",
            ),
        ),
        migrations.AlterField(
            model_name="sofdata",
            name="extracted_data",
            field=models.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name="sofdocument",
            name="file",
            field=models.FileField(upload_to=pipeline.models.user_directory_path),
        ),
        migrations.AlterField(
            model_name="sofdocument",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("word", "Word")], max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="sofdocument",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
